events:
  - event_id: "353"
    event_name: "Valorant Champions Tour Stage 2: Masters Reykjavík"
    match_urls: []   # leave blank to auto–scrape all matches
    match_ids: []    # optional override if you ever want to target specific matches